# Generated by Django 4.2.13 on 2025-01-16 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content",
                    models.TextField(blank=True, null=True, verbose_name="Comment"),
                ),
                (
                    "date_posted",
                    models.DateTimeField(
                        auto_now_add=True, null=True, verbose_name="Created By"
                    ),
                ),
                ("quoted_text", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-date_posted"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "restaurant_name",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Restaurant"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=150,
                        null=True,
                        verbose_name="Address",
                    ),
                ),
                (
                    "tips_situation",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("TG", "Tips Given"),
                            ("TNG", "Tips Not Given"),
                            ("C", "Conditional"),
                        ],
                        max_length=10,
                        null=True,
                        verbose_name="Tips Situation",
                    ),
                ),
                (
                    "tips_sit_detail",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Describe"
                    ),
                ),
                (
                    "food_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ITL", "Italian"),
                            ("CHI", "Chinese"),
                            ("JPN", "Japanese"),
                            ("IND", "Indian"),
                            ("FRE", "French"),
                            ("MEX", "Mexican"),
                            ("GRK", "Greek"),
                            ("THA", "Thai"),
                            ("SPA", "Spanish"),
                            ("AMR", "American"),
                            ("MED", "Mediterranean"),
                            ("KOR", "Korean"),
                            ("VIE", "Vietnamese"),
                            ("TUR", "Turkish"),
                            ("CUB", "Cuban"),
                            ("CAR", "Caribbean"),
                            ("GER", "German"),
                            ("ETH", "Ethiopian"),
                            ("LEB", "Lebanese"),
                            ("MOR", "Moroccan"),
                            ("BRZ", "Brazilian"),
                            ("ARG", "Argentinian"),
                            ("PER", "Peruvian"),
                            ("POR", "Portuguese"),
                            ("SWE", "Swedish"),
                            ("POL", "Polish"),
                            ("ISR", "Israeli"),
                            ("AFG", "Afghan"),
                            ("PAK", "Pakistani"),
                            ("BAN", "Bangladeshi"),
                            ("NEP", "Nepalese"),
                            ("TIB", "Tibetan"),
                            ("PHI", "Filipino"),
                            ("MAL", "Malaysian"),
                            ("SRI", "Sri Lankan"),
                            ("HUN", "Hungarian"),
                            ("CZE", "Czech"),
                            ("RUS", "Russian"),
                            ("UKR", "Ukrainian"),
                            ("ROM", "Romanian"),
                            ("SEN", "Senegalese"),
                            ("NIG", "Nigerian"),
                            ("ETH", "Ethiopian"),
                            ("KEN", "Kenyan"),
                            ("ZAF", "South African"),
                            ("EGY", "Egyptian"),
                            ("SAF", "South American Fusion"),
                            ("MIX", "Mixed Cuisine"),
                            ("BBQ", "Barbecue"),
                            ("SEA", "Seafood"),
                            ("VEG", "Vegetarian"),
                            ("VGN", "Vegan"),
                            ("GLT", "Gluten-Free"),
                            ("DST", "Desserts"),
                            ("SNK", "Snacks"),
                            ("BRK", "Breakfast"),
                            ("BKT", "Bakery"),
                        ],
                        max_length=3,
                        null=True,
                        verbose_name="Food Type",
                    ),
                ),
                (
                    "job_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("FT", "Full-time"),
                            ("PT", "Part-time"),
                            ("CON", "Contract"),
                            ("TMP", "Temporary"),
                        ],
                        max_length=3,
                        null=True,
                        verbose_name="Job Type",
                    ),
                ),
                ("date", models.DateField(verbose_name="Date")),
                ("content", models.TextField(max_length=1000, verbose_name="Detail")),
                ("release_date", models.DateTimeField(verbose_name="Now")),
                (
                    "slug",
                    models.SlugField(blank=True, default="", max_length=100, null=True),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.CharField(blank=True, max_length=1000, null=True)),
                ("link", models.CharField(blank=True, max_length=1000, null=True)),
                (
                    "reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("SPAM", "Spam"),
                            ("HATE", "Hate"),
                            ("FALSE", "False Statement"),
                            ("HARASSMENT", "Harassment"),
                            ("THREATENING", "Threatening Violence"),
                            ("ABUSE", "Abuse or Sexualization"),
                            ("PERSONAL", "Sharing Personal Information"),
                            ("SUICIDE", "Self-harm or Suicide"),
                            ("IMPERSONATION", "Impersonation"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                ("detail", models.TextField(blank=True, max_length=1000, null=True)),
                ("date_reported", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
