# Generated by Django 4.2.13 on 2025-02-07 02:35

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="otptoken",
            name="verification_token",
            field=models.CharField(default=secrets.token_urlsafe, max_length=100),
        ),
    ]
