# PROVINCE_CHOICES = [
#     ('AB', 'Alberta'),
#     ('BC', 'British Columbia'),
#     ('MB', 'Manitoba'),
#     ('NB', 'New Brunswick'),
#     ('NL', 'Newfoundland and Labrador'),
#     ('NS', 'Nova Scotia'),
#     ('ON', 'Ontario'),
#     ('PE', 'Prince Edward Island'),
#     ('QC', 'Quebec'),
#     ('SK', 'Saskatchewan'),
#     ('NT', 'Northwest Territories'),
#     ('NU', 'Nunavut'),
#     ('YT', 'Yukon'),
# ]
#
# CITY_CHOICES = [
#     #AB 0 - 9
#     ('CAL', 'Calgary'),
#     ('EDM', 'Edmonton'),
#     ('RED', 'Red Deer'),
#     ('LET', 'Lethbridge'),
#     ('MED', 'Medicine Hat'),
#     ('GRP', 'Grande Prairie'),
#     ('STU', 'St. Albert'),
#     ('AIR', 'Airdrie'),
#     ('SPU', 'Spruce Grove'),
#     ('LLO', 'Lloydminster'),
#     #BC 10 - 19
#     ('VAN', 'Vancouver'),
#     ('VIC', 'Victoria'),
#     ('SUR', 'Surrey'),
#     ('BUR', 'Burnaby'),
#     ('RCH', 'Richmond'),
#     ('ABB', 'Abbotsford'),
#     ('COQ', 'Coquitlam'),
#     ('KEL', 'Kelowna'),
#     ('NAN', 'Nanaimo'),
#     ('KAM', 'Kamloops'),
#     #MB 20 - 29
#     ('WIN', 'Winnipeg'),
#     ('BRN', 'Brandon'),
#     ('STE', 'Steinbach'),
#     ('THO', 'Thompson'),
#     ('POR', 'Portage la Prairie'),
#     ('WSE', 'Winkler'),
#     ('SEL', 'Selkirk'),
#     ('MOR', 'Morden'),
#     ('DAU', 'Dauphin'),
#     ('FLI', 'Flin Flon'),
#     #NB 30 - 39
#     ('FRE', 'Fredericton'),
#     ('MON', 'Moncton'),
#     ('STJ', 'Saint John'),
#     ('DIE', 'Dieppe'),
#     ('RIV', 'Riverview'),
#     ('QUA', 'Quispamsis'),
#     ('ROT', 'Rothesay'),
#     ('EDM', 'Edmundston'),
#     ('BTH', 'Bathurst'),
#     ('CMA', 'Campbellton'),
#     #NL 40 - 49
#     ('STJ', 'St. John\'s'),
#     ('MOU', 'Mount Pearl'),
#     ('CBS', 'Conception Bay South'),
#     ('PAR', 'Paradise'),
#     ('COR', 'Corner Brook'),
#     ('GFW', 'Grand Falls-Windsor'),
#     ('GAN', 'Gander'),
#     ('LAB', 'Labrador City'),
#     ('CAR', 'Carbonear'),
#     ('HAP', 'Happy Valley-Goose Bay'),
#     #NS 50 - 59
#     ('HAL', 'Halifax'),
#     ('SYD', 'Sydney'),
#     ('DTR', 'Dartmouth'),
#     ('BED', 'Bedford'),
#     ('TRU', 'Truro'),
#     ('NAN', 'New Glasgow'),
#     ('GLA', 'Glace Bay'),
#     ('KNG', 'Kings County'),
#     ('AMH', 'Amherst'),
#     ('YAR', 'Yarmouth'),
#     #ON 60 - 69
#     ('TOR', 'Toronto'),
#     ('OTT', 'Ottawa'),
#     ('MIS', 'Mississauga'),
#     ('BRM', 'Brampton'),
#     ('HAM', 'Hamilton'),
#     ('LON', 'London'),
#     ('MAR', 'Markham'),
#     ('VGN', 'Vaughan'),
#     ('KIN', 'Kingston'),
#     ('GUEL', 'Guelph'),
#     #PE 70 - 79
#     ('CHA', 'Charlottetown'),
#     ('SUM', 'Summerside'),
#     ('STR', 'Stratford'),
#     ('COR', 'Cornwall'),
#     ('MON', 'Montague'),
#     ('KNS', 'Kensington'),
#     ('SOR', 'Souris'),
#     ('ALB', 'Alberton'),
#     ('TIG', 'Tignish'),
#     ('OGY', 'O\'Leary'),
#     #QC 80 - 89
#     ('MTL', 'Montreal'),
#     ('QBC', 'Quebec City'),
#     ('LAV', 'Laval'),
#     ('GAT', 'Gatineau'),
#     ('LON', 'Longueuil'),
#     ('SHR', 'Sherbrooke'),
#     ('SAG', 'Saguenay'),
#     ('TRO', 'Trois-Rivières'),
#     ('TER', 'Terrebonne'),
#     ('REP', 'Repentigny'),
#     #SK 90 - 99
#     ('SAS', 'Saskatoon'),
#     ('REG', 'Regina'),
#     ('PRN', 'Prince Albert'),
#     ('MOS', 'Moose Jaw'),
#     ('YOR', 'Yorkton'),
#     ('SWI', 'Swift Current'),
#     ('NBR', 'North Battleford'),
#     ('MEL', 'Melville'),
#     ('EST', 'Estevan'),
#     ('WEY', 'Weyburn'),
#     #NT 100 - 109
#     ('YEL', 'Yellowknife'),
#     ('HAY', 'Hay River'),
#     ('FBF', 'Fort Smith'),
#     ('INU', 'Inuvik'),
#     ('NOR', 'Norman Wells'),
#     ('TUK', 'Tuktoyaktuk'),
#     ('FTS', 'Fort Simpson'),
#     ('FTM', 'Fort McPherson'),
#     ('DEL', 'Deline'),
#     ('AUL', 'Aulavik'),
#     #NU 110 - 119
#     ('IQ', 'Iqaluit'),
#     ('RAN', 'Rankin Inlet'),
#     ('CBT', 'Cambridge Bay'),
#     ('ARV', 'Arviat'),
#     ('BAK', 'Baker Lake'),
#     ('PAN', 'Pangnirtung'),
#     ('CBB', 'Clyde River'),
#     ('IGL', 'Igloolik'),
#     ('CHE', 'Chesterfield Inlet'),
#     ('HAL', 'Hall Beach'),
#     #YT 120 - 129
#     ('WHT', 'Whitehorse'),
#     ('DAW', 'Dawson City'),
#     ('WAT', 'Watson Lake'),
#     ('HEN', 'Haines Junction'),
#     ('CAR', 'Carmacks'),
#     ('FAR', 'Faro'),
#     ('MAS', 'Mayo'),
#     ('ROC', 'Ross River'),
#     ('PCL', 'Pelly Crossing'),
#     ('OLD', 'Old Crow'),
# ]

FOOD_TYPE_CHOICES = [
    ('ITL', 'Italian'),
    ('CHI', 'Chinese'),
    ('JPN', 'Japanese'),
    ('IND', 'Indian'),
    ('FRE', 'French'),
    ('MEX', 'Mexican'),
    ('GRK', 'Greek'),
    ('THA', 'Thai'),
    ('SPA', 'Spanish'),
    ('AMR', 'American'),
    ('MED', 'Mediterranean'),
    ('KOR', 'Korean'),
    ('VIE', 'Vietnamese'),
    ('TUR', 'Turkish'),
    ('CUB', 'Cuban'),
    ('CAR', 'Caribbean'),
    ('GER', 'German'),
    ('ETH', 'Ethiopian'),
    ('LEB', 'Lebanese'),
    ('MOR', 'Moroccan'),
    ('BRZ', 'Brazilian'),
    ('ARG', 'Argentinian'),
    ('PER', 'Peruvian'),
    ('POR', 'Portuguese'),
    ('SWE', 'Swedish'),
    ('POL', 'Polish'),
    ('ISR', 'Israeli'),
    ('AFG', 'Afghan'),
    ('PAK', 'Pakistani'),
    ('BAN', 'Bangladeshi'),
    ('NEP', 'Nepalese'),
    ('TIB', 'Tibetan'),
    ('PHI', 'Filipino'),
    ('MAL', 'Malaysian'),
    ('SRI', 'Sri Lankan'),
    ('HUN', 'Hungarian'),
    ('CZE', 'Czech'),
    ('RUS', 'Russian'),
    ('UKR', 'Ukrainian'),
    ('ROM', 'Romanian'),
    ('SEN', 'Senegalese'),
    ('NIG', 'Nigerian'),
    ('ETH', 'Ethiopian'),
    ('KEN', 'Kenyan'),
    ('ZAF', 'South African'),
    ('EGY', 'Egyptian'),
    ('SAF', 'South American Fusion'),
    ('MIX', 'Mixed Cuisine'),
    ('BBQ', 'Barbecue'),
    ('SEA', 'Seafood'),
    ('VEG', 'Vegetarian'),
    ('VGN', 'Vegan'),
    ('GLT', 'Gluten-Free'),
    ('DST', 'Desserts'),
    ('SNK', 'Snacks'),
    ('BRK', 'Breakfast'),
    ('BKT', 'Bakery'),
]

JOB_TYPE_CHOICES = [
    ('FT', 'Full-time'),
    ('PT', 'Part-time'),
    ('CON', 'Contract'),
    ('TMP', 'Temporary'),
]

TIPS_SITUATION_CHOICES = [
    ('TG', 'Tips Given'),
    ('TNG', 'Tips Not Given'),
    ('C', 'Conditional'),
]

REASON_CHOICES = [
    ('SPAM', 'Spam'),
    ('HATE', 'Hate'),
    ('FALSE', 'False Statement'),
    ('HARASSMENT', 'Harassment'),
    ('THREATENING', 'Threatening Violence'),
    ('ABUSE', 'Abuse or Sexualization'),
    ('PERSONAL', 'Sharing Personal Information'),
    ('SUICIDE', 'Self-harm or Suicide'),
    ('IMPERSONATION', 'Impersonation'),
]